### ISSUE TITLE
Styling not taking affect on mobile devices

### ISSUE THREAD

**Issue by annumberhocker** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#120]
The website isn't adjusting font size and stacking when on mobile device.  The hamburger menu appears, but is so small, it isn't usable.  Here are images take from Iphone xs and an Android 
![image](https://user-images.githubusercontent.com/38887336/96401345-99ebca00-1198-11eb-9e36-794c155a5d61.png)

**Comment by annumberhocker** [comment]
It looks like the website is responsive now on both Iphone and Android (possibly a deployment problem).  However, the Hero quote and description are being cut off on an android phone.  @sydbails  to look at putting a min-height requirement on the component.

**Comment by davidnixon** [comment]
fixed
