### ISSUE TITLE
Submit selfie videos to Five Fifths Box Folder 

### ISSUE THREAD

**Issue by aleggett23** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#121]
Team! Please submit videos for promo videos following the instructions below:
Submissions by **10.21.20 by 5pm.** 
**_Please submit them here:_**  https://ibm.box.com/s/z3rdvxozfr3gdm9jtpun6qa2y5yecuds

**Aim for about 30-60 seconds in your answer.** 
**Please submit your videos as .mp4 or .mov files**
**When naming your video files, follow this format: name - question that is answered.mp4**

**Questions**
What inspired you to participate in Call for Code for Racial Justice? 
What is the problem you set out to solve with your solution? 
What is the background to this project - is this related to an issue you have personally faced? 
How does your solution solve the problem? 
Specifically, who will your solution help, and how will it achieve that? 
What technology did you use to build your solution? 
For anyone looking to become an open source contributor to the project, what guidance would you give them? In other words, where does the solution need help from an open source community? 
What does success look like for this project going forward? 

**Self-recording tips:**
-Find a well-lit location to set up your phone or computer to record yourself.
-Speak directly to your camera lens and if you can avoid it, don’t read your answers from a prepared statement.
_ Speaking “off-the-cuff” will give a more authentic feel to your video.
_**You can either answer all questions in one file or answer each question separately**
-Ensure that your lighting source is front-facing and that we can see your face clearly
-Sit close enough to your recording device that it can easily pick up your audio. You can do a quick test to check your lighting/audio/video.

**Comment by drealuc** [comment]
Completed.
