### ISSUE TITLE
Remove "Embrace The Vote" Name from Architecture Design on README 

### ISSUE THREAD

**Issue by aleggett23** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#122]

**Comment by sydbails** [comment]
![arch1](https://user-images.githubusercontent.com/47571589/96465719-e530c780-11ee-11eb-8880-c57fac7a429a.png)
![arch2](https://user-images.githubusercontent.com/47571589/96465731-e7932180-11ee-11eb-8eaf-4adad7fa5ae2.png)

I quickly changed the titles on these in photoshop. @blumareks will go over this later today, make necessary updates and add to the ReadMe.

**Comment by davidnixon** [comment]
See #123

**Comment by drealuc** [comment]
Corrected
