### ISSUE TITLE
Need to add  vote411.org in Readme.  

### ISSUE THREAD

**Issue by annumberhocker** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#123]
On the "Get Informed" page, when a state is selected, the user is provided a link to the state specific voting information via the vote411.org website.  This includes specific id requirements, polling locations, drop off locations, etc.  

The "vote411.org" website needs to be added to the architecture diagrams in lieu of Secretary of State and in the "Data Set" section.

**Comment by davidnixon** [comment]
@ydknorr can we are using vote411.org on the "get informed" page. Can you verify that this is ok.

**Comment by drealuc** [comment]
@davidnixon I will take the action to update the datasets section and the solution overview doc on the readme.

**Comment by drealuc** [comment]
Added to readme
