### ISSUE TITLE
Update README with ZenHub plug in instructions

### ISSUE THREAD

**Issue by drealuc** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#134]
Add instructions to readme for ZenHub plug-in install

Reviewing this tool to determine usefulness in managing the Five Fifths project.

**Comment by lidderupk** [comment]
Zenhub is free to use for open source projects. See here - https://blog.zenhub.com/open-source/

```No license is required to use ZenHub on public or open-source repositories: simply download ZenHub and sign in to GitHub. Most academic projects fall into this category.```

**Comment by drealuc** [comment]
ZenHub can be used for GitHub view to facilitate agile workflow
