### ISSUE TITLE
Experiments to resolve "Too Many Requests" error

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#144]
# Background
See #142 
Currently the python code that provides the twitter data for the app requests the 5 most recent tweets for the given screen name.
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/1f460524ca2f3d33469205d57d58ee54629cefb4/services/twitter/Chatter.py#L155-L158
But previously the code requested the 25 most recent tweets.

Then, for each tweet, the python code calls the NLU to get sentiments and emotion scores.
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/1f460524ca2f3d33469205d57d58ee54629cefb4/services/twitter/Chatter.py#L50-L56

See this for more  [NLU API docs](https://cloud.ibm.com/apidocs/natural-language-understanding?code=python#analyze)

For our lite plan, the API is rate limited to 5 calls per second.
From the IBM docs:
> Request limit
> Each Natural Language Understanding service instance is limited, based on the number of requests being processed. For the Lite plan, the limit is 5 requests per second; ... Requests exceeding these limits may receive a 429: Too Many Requests error.

To process more than 5 tweets we would need to upgrade to a paid plan or change how we call the API. 

# One idea for an Experiment 

The NLU api accepts "emotion.targets" and "sentiment.targets" as an array of strings.
If we set `text` to the concatenation of all 25 tweets and we set `emotion.targets` and `sentiment.targets` to the individual tweets, could we submit **1** request to NLU instead of 25 and get the proper response?

Other ideas to reduce the number of calls to NLU?

# Notes
Because multiple end user may click the twitter button in the UI, even processing 5 tweets may fail. So the current solution may, as Alexandria pointed out, still fail. Ultimately we probably do want to upgrade to a paid NLU services but even then it would be more efficient to process multiple tweets with 1 API call.

# Related
I do not think we saw any issues with the tone analyzer but the same "Too Many Requests" issue is probably there. The code makes multiple calls to the tone analyzer but perhaps there is a way to make a single call for each set of tweets.
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/1f460524ca2f3d33469205d57d58ee54629cefb4/services/twitter/Chatter.py#L71-L75

**Comment by cstefano1** [comment]
Would be resolved if we paid for IBM services.
