### ISSUE TITLE
Enable internationalizations (I18N)

### ISSUE THREAD

**Issue by drealuc** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#149]

**Comment by cstefano1** [comment]
@upkarlidder I heard through the grapevine that you might be working on this.  If so, please assign yourself.  :)  Thx

**Comment by upkarlidder** [comment]
Started #192 to externalize strings.

Sample in Hindi:

![image](https://user-images.githubusercontent.com/3187457/129991218-8d60f340-a3ca-43d8-828d-11320cdba8b0.png)

**Comment by upkarlidder** [comment]
I have externalized the majority of strings. For anything left, we can create new issues.

Okay to close this @davidnixon, @cstefano1?

**Comment by cstefano1** [comment]
@upkarlidder I defer to @davidnixon .  Thx
