### ISSUE TITLE
Extract English language strings

### ISSUE THREAD

**Issue by drealuc** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#150]
Depends on #149

**Comment by cstefano1** [comment]
@upkarlidder I heard through the grapevine that you might be working on this.  If so, please assign yourself.  :)  Thx

**Comment by upkarlidder** [comment]
I have externalized the majority of strings. For anything left, we can create new issues.

Okay to close this @davidnixon, @cstefano1?

**Comment by cstefano1** [comment]
Thanks @upkarlidder.  I defer to @davidnixon .

**Comment by davidnixon** [comment]
Ok with me. closing.
