### ISSUE TITLE
Update docs to remove Mongodb

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#154]
We used to use Mongo in deployment and locally but not anymore. We switch the deployment from Open Shift to cloud foundry and as part of that we switch to Cloudant in production and Couch db for local development.

The services readme needs to be updated with this information but also a scrub of any other references to Mongo needs to be done.

**Comment by hluko** [comment]
@davidnixon Hey David, the issue title references updating docs, should we also remove any mongo code in the repo?

**Comment by upkarlidder** [comment]
Thanks @hluko. @davidnixon has removed mongo from the code. Please feel free to remove any occurrences from the readmes. I see one here - https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/16faf534b811f77afbcbf670f21fd69e283f0c83/services/README.md

Create a PR when done.

**Comment by cstefano1** [comment]
@upkarlidder Is this actually closed?  Looks like Automation closed it.

**Comment by upkarlidder** [comment]
This is still open. There is one occurrence of Mongo in the [README.md](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/main/services/README.md) file.

@hluko would you like to pick this up for HacktoberFest?

**Comment by gibrankasif** [comment]
Hi @upkarlidder may I take up this issue?

**Comment by demilolu** [comment]
hi @gibrankasif can you link your PR to this issue please, thanks!

**Comment by GeraldMit** [comment]
Hi @gibrankasif your change was merged 
@davidnixon agreement to close?
