### ISSUE TITLE
Get Connected - tweet sentiments 

### ISSUE THREAD

**Issue by orazgeldiyevanazik** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#155]
**Current state :** sentiment of the tweet is labeled in text.

**Proposed state :** color code tweets to improve readability and to display importance. Additional toggle for color coding  feature. 

**Questions and concerns:** 

- What colors should we use for positive, negative and neutral tweet sentiments? 
- Should we use colors from [carbon design system](https://www.carbondesignsystem.com/guidelines/color/overview/)?  
- If so, which specific shades should we use?

-  What accessibility solutions exist for people who are color blind?

**Comment by drealuc** [comment]
Hi @orazgeldiyevanazik! We will get back with you soonest.

**Comment by orazgeldiyevanazik** [comment]
We designed three options:

Image 1: Color borders for positive (green), negative (red) and neutral (yellow or blue).
![imageGit01](https://user-images.githubusercontent.com/78379956/108760808-bc5d6d80-7513-11eb-9372-2bbfcca9d94f.PNG)

Image 2: Divider between tweets - spacing too.
![imageGit02](https://user-images.githubusercontent.com/78379956/108760809-bcf60400-7513-11eb-9580-f64e30d846d3.PNG)

Image 3: Color highlights - different colors for positive, negative and neutral. 
![imageGit03](https://user-images.githubusercontent.com/78379956/108760810-bcf60400-7513-11eb-9462-0232dcfc17ae.PNG)

**Comment by drealuc** [comment]
@orazgeldiyevanazik @sebastianhuynh @aleggett23 @davidnixon I think image 1, color borders are the cleanest. I also want our lead designed to weigh in. I will follow up with him soonest

**Comment by aleggett23** [comment]
I also like the colors in image 1, though I also like image 3 for visibility. @orazgeldiyevanazik , is there any way to see how different colors would look in image #3 ? like possibly Red for negative, yellow for neutral, and green for positive?

**Comment by sebastianhuynh-nyc** [comment]
Hello and thank you so much for asking, 
I will provide my answers in italic under your questions, and please do keep reaching out!

Current state : sentiment of the tweet is labeled in text.

Proposed state : color code tweets to improve readability and to display importance. Additional toggle for color coding feature.
_I can see the want to add a color to help differentiate, however we have to be careful to apply color over a dark background, we run into a lot of issues of accessibility and readability. Maybe we can devise a device where each tweet is isolated into a container with some kind of signifier- either a badge or some visual cue?_

Questions and concerns:

What colors should we use for positive, negative and neutral tweet sentiments?
_for positive I would recommend green and Negative would be yellow and neutral sentiment would be a blue._ 

Should we use colors from carbon design system?
_Yes, it would be a good starting point, but being an open source project, feel free to own the project and give it some of your personality_

If so, which specific shades should we use?

What accessibility solutions exist for people who are color blind?
_Please start here for accessibility concerns, 
https://www.carbondesignsystem.com/guidelines/accessibility/overview/_

Please do reach out with any more questions, 
Stay Well
Sebastian Huynh

**Comment by cstefano1** [comment]
#132

**Comment by GeraldMit** [comment]
I happen to be red-green colorblind. 
I recommend not using red-green as that is a color pairing that those with color-blindness can't discern. In general, red yellow blue may be easier to discern. Also consider not coloring neutral at all (as it is the base state) as yellow is more visible on black than red.
I was also thinking that the a full border may draw too much attention to separation of each tweet.  thoughts on just the left and right border?
