### ISSUE TITLE
Local development issue on Windows in database folder

### ISSUE THREAD

**Issue by aharkenaa** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#156]
We ran into some issues on Windows with building the Docker image for CouchDB and the default Windows line endings CRLF causing the packaged shell scripts to break. I've added a `.gitattributes` file and made a (very small) PR on the American Airlines fork but wanted to open an issue here to link the PR to and get feedback.

https://github.com/AmericanAirlines/Five-Fifths-Voter/pull/1

**Comment by davidnixon** [comment]
Added this to #196
