### ISSUE TITLE
Getting 503 error when looking for polling location

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#160]
Steps:
1. Go to https://www.fivefifthsvoter.com/#/journey
2. Click on `Voter Journey` and then `Vote`
   ![image](https://user-images.githubusercontent.com/3187457/121401929-286eb080-c90e-11eb-8034-51c24828cec1.png)
3. Add an address and click on `Polling Location`.
4. The browser console shows an error:
```
VM7:1 POST https://www.fivefifthsvoter.com/services/pollingplace 503 (Service Unavailable)
```
![image](https://user-images.githubusercontent.com/3187457/121402174-6d92e280-c90e-11eb-9425-05dcd5a426be.png)

**Comment by upkarlidder** [comment]
@davidnixon looks like `https://civicinfo.googleapis.com/civicinfo/v2/voterinfo` needs an API key. Is this a recent change? I don't see this being set up in the READMEs. Does five-fifth have a Google account we can use to generate the key? Thank you.

FYI @aleggett23

**Comment by aleggett23** [comment]
Hi Upkar! 
 
I will take a look, I believe that may have been an addition made by the ADEPT Team. We also are having a team call this week regarding an overview of the Design Thinking Session and Next Steps. I will send you an invite as well.
 
 
Alexandria Leggett
Expert Labs Data & A.I.
IBM Cloud and Cognitive Software 🌩
E-mail: ***@***.***
Phone: (404)-804-2463
 
 
----- Original message -----From: Upkar Lidder ***@***.***>To: Call-for-Code-for-Racial-Justice/Five-Fifths-Voter ***@***.***>Cc: aleggett23 ***@***.***>, Mention ***@***.***>Subject: [EXTERNAL] Re: [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter] Getting 503 error when looking for polling location (#160)Date: Mon, Jun 14, 2021 12:32 AM      @davidnixon looks like https://civicinfo.googleapis.com/civicinfo/v2/voterinfo needs an API key. Is this a recent change? I don't see this being set up in the READMEs. Does five-fifth have a Google account we can use to generate the key? Thank    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@davidnixon looks like https://civicinfo.googleapis.com/civicinfo/v2/voterinfo needs an API key. Is this a recent change? I don't see this being set up in the READMEs. Does five-fifth have a Google account we can use to generate the key? Thank you.
FYI @aleggett23

**Comment by upkarlidder** [comment]
Thank you @aleggett23. Some thoughts assuming the feature will be used moving forward:

- we should show an error to the user if the call fails for any reason (including missing API key). Something like `We could not get polling locations at this time, please try again later.`
- we should document the need for the API key. I am guessing this was a recent change on the Google API side and therefore not captured in the docs.

**Comment by davidnixon** [comment]
@upkarlidder I'm not sure what is happening. We do have a civic API here and it is provisioned to the app via this services:
![image](https://user-images.githubusercontent.com/7536103/122067617-b68ce000-cdc1-11eb-9638-01afb1d54643.png)
You can see this under "Cloud Foundry services"

When I log into my Google API account I can see it is return 100% errors. Looking into why ...

**Comment by davidnixon** [comment]
I checked the value in the VCAP runtime and it does match the correct API key value.
![image](https://user-images.githubusercontent.com/7536103/122071352-ae826f80-cdc4-11eb-8ce2-e4a7eed45e72.png)

@upkarlidder You are correct though that this information is missing from the README for local dev
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/tree/main/services#local-dev

It should mention that locally you need to set NODE_GOOGLE_CIVIC_API_KEY in your .env file. For local development that needs this functionality, developers should get their own key from the Google.

**Comment by upkarlidder** [comment]
Thank you @davidnixon. Sounds good. I am also happy to edit the README and contribute back if you like.

**Comment by cstefano1** [comment]
I tried to replicate the original error.  In Chrome, when I go to www.fivefifthsvoter.com, I get "Your connection is not private" error.  
![image](https://user-images.githubusercontent.com/35705510/126705379-52930f89-3545-4794-8b40-c441ff879746.png)

When I do get to the site and go to Voter Journey > Vote, then enter an address, the site doesn't respond whether I click Early Voting or Polling Location.  (It's doesn't error out; just does nothing....)  

I know I'm late to the party.  What do we want it to do?

**Comment by davidnixon** [comment]
@GeraldMit As we discussed with Chris on Friday, the user needs to be able to select the election that she is interested in. So the polling place page needs an extra field on it which needs to be populated and then passed to the backend.

**AS-IS**
![image](https://user-images.githubusercontent.com/7536103/127783891-525f6eca-8fee-473f-8d85-ba3811718a4e.png)

**Add Drop Down**
https://vue.carbondesignsystem.com/?path=/story/components-cvdropdown--vmodel
![image](https://user-images.githubusercontent.com/7536103/127783900-5c42590a-bedf-420e-abaf-a37322e6a151.png)


You can get the values for upcoming elections by calling axios like this. 
```javascript
  created() {
    axios
      .get('/services/elections')
      .then((response) => {
        this.elections = response.data.elections
      })
      .catch((error) => {
        /* eslint no-console: 0 */
        console.error(error)
      })
  },
```

You will get a response like this:
```json
{
    "elections": [
        {
            "electionDay": "2025-06-06",
            "id": "2000",
            "name": "VIP Test Election",
            "ocdDivisionId": "ocd-division/country:us"
        },
        {
            "electionDay": "2021-08-03",
            "id": "7041",
            "name": "Washington Election",
            "ocdDivisionId": "ocd-division/country:us/state:wa"
        },
        {
            "electionDay": "2021-08-10",
            "id": "7042",
            "name": "Minnesota Election",
            "ocdDivisionId": "ocd-division/country:us/state:mn"
        },
        {
            "electionDay": "2021-08-10",
            "id": "7043",
            "name": "Oklahoma Election",
            "ocdDivisionId": "ocd-division/country:us/state:ok"
        },
        {
            "electionDay": "2021-08-03",
            "id": "7082",
            "name": "Michigan State Senate and Municipal Election",
            "ocdDivisionId": "ocd-division/country:us/state:mi"
        },
        {
            "electionDay": "2021-08-10",
            "id": "7135",
            "name": "Utah Municipal Election",
            "ocdDivisionId": "ocd-division/country:us/state:ut"
        }
    ],
    "kind": "civicinfo#electionsQueryResponse"
}
```

You should ignore the `"id": "2000",` which is a fake election meant for testing only.

So you should end up with something like this in `src/components/EarlyVoting/EarlyVoting.vue`:
```vue
    <cv-dropdown v-model="electionId" label="Select election" placeholder="Choose an election">
      <cv-dropdown-item v-for="elec in fileredElections" :value="elec.id" :key="elec.id">
        {{ elec.name }} {{ elec.electionDay }}</cv-dropdown-item
      >
    </cv-dropdown>

// ...
data: () => ({
    electionId: '',
// ...

computed: {
    fileredElections() {
      return this.elections.filter((item) => item.id != '2000')
    },

// ...
```

So then in the `showPollingLocation` methods just include that electionId in the payload.

On the backend edit `services/routes/civic.js` and use the electionId from the payload instead of the one defined in that file.

**Comment by davidnixon** [comment]
@GeraldMit @upkarlidder I added links to the google console in the services README. Gerald you will need a key to work on this locally. In production we use a different key.

> Developers should request and maintain their own personal Google Civics API key to work with those services.
> https://console.cloud.google.com/
> https://developers.google.com/civic-information/docs/using_api

@cstefano1 I scheduled a meeting with @yrabun  to resolve the "your connection is not private"

**Comment by aleggett23** [comment]
Thank you all!
Alexandria Leggett
Expert Labs Data & A.I. Principal
IBM Cloud and Cognitive Software 🌩
E-mail: ***@***.***
Phone: (404)-804-2463
 
 
----- Original message -----From: "David Nixon" ***@***.***>To: "Call-for-Code-for-Racial-Justice/Five-Fifths-Voter" ***@***.***>Cc: "aleggett23" ***@***.***>, "Mention" ***@***.***>Subject: [EXTERNAL] Re: [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter] Getting 503 error when looking for polling location (#160)Date: Sun, Aug 1, 2021 4:42 PM      @GeraldMit @upkarlidder I added links to the google console in the services README. Gerald you will need a key to work on this locally. In production we use a different key. Developers should request and maintain their own personal Google Civics    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@GeraldMit @upkarlidder I added links to the google console in the services README. Gerald you will need a key to work on this locally. In production we use a different key.
Developers should request and maintain their own personal Google Civics API key to work with those services.https://console.cloud.google.com/https://developers.google.com/civic-information/docs/using_api
@cstefano1 I scheduled a meeting with @yrabun to resolve the "your connection is not private"
