### ISSUE TITLE
Updates to Five Fifths Voter Tutorial

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#162]
# Background
As a person interested in contributing to the Five Fifths Voter open source project, I'm looking to complete the [tutorial](https://developer.ibm.com/tutorials/five-fifths-voter/). However, as a new developer, I'm having some issues with the tutorial. 

# Problem 

Tutorial is missing a step after 
`git clone https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter`
so that` cd services ` leads to an error

# Suggested Solution
add an additional step so that we are in the right directory:
1. `git clone https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter`
2. `cd Five-Fifths-Voter`

**Comment by upkarlidder** [comment]
I am looking at the tutorials with the authors to see if they can be updated to reflected latest changes in GitHub.

Testing to see if this comment removes the stale label.
