### ISSUE TITLE
amplitude cookie rejection warning

### ISSUE THREAD

**Issue by GeraldMit** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#163]
**Describe the bug**
Seen when opening the browser console in Firefox.

Some cookies are misusing the recommended “SameSite“ attribute 6
Cookie “amplitude_cookie_test” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite amplitude.js:1476:2

Cookie “amplitude_cookie_test” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite amplitude.js:1476:2

Cookie “__tld_test__” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 amplitude.js:1476:2

Cookie “amplitude_testfivefifthsvoter.com” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 amplitude.js:1476:2

Cookie “amplitude_id_ce77e3704c5ecc2461e846f3061022c2fivefifthsvoter.com” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite amplitude.js:1476:2

Cookie “amplitude_id_ce77e3704c5ecc2461e846f3061022c2fivefifthsvoter.com” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**To Reproduce**
1. Use Firefox latest
2. pen javascript console
3. Go to  https://www.fivefifthsvoter.com/#/journey

**Expected behavior**
Not to have cookie warnings

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.15.7
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 89.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by davidnixon** [comment]
@GeraldMit https://developers.amplitude.com/docs/advanced-settings#cookie-management

It looks like this is the right doc to help resolve this. There is a section on setting the SameSite attribute. https://developers.amplitude.com/docs/advanced-settings#samesite

**Comment by demilolu** [comment]
has this been fixed? @GeraldMit 

cc: @upkarlidder

**Comment by GeraldMit** [comment]
No longer seeing it, on my current machine and Firfefox.
