### ISSUE TITLE
Add stale bot for older issues

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#164]
Use a stale action to alert maintainers to issues and PRs that have been sitting idle for a while. The `staleness` is reset if somebody comments on the issue. This forces the team to address outstanding issues and PRs.

https://github.com/actions/stale

Default configuration:

1. Add a label "Stale" on issues and pull requests after 60 days of inactivity
2. Close the stale issues and pull requests after 7 days of inactivity
3. If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart

@davidnixon @GeraldMit @Sabine-Justilien @demilolu, et al.  - what do you think?

**Comment by GeraldMit** [comment]
concerned that 7 days is short due to open source. 14 days?

**Comment by upkarlidder** [comment]
Absolutely. The default is 7 days. We can configure to what makes sense for us.
