### ISSUE TITLE
Be able to interact with other account users and share voting experience

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#189]
### Background on the problem the feature will solve/improved user experience
Per the Roadmap from our Design Thinking session

### Describe the solution you'd like
Be able to interact with other account users and share voting experience(timeline, etc)

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by aleggett23** [comment]
Description: 

>  Account users with logins can chat/interact with one another and share/comment/post content on a timeline 

> Users will have the option to interact on the timeline globally with all other users, or they can choose to filter the feed. 
  

> By filtering, users can choose to only interact with a particular geographical area or only with certain shared interests depending on the user’s selected preferences.
