### ISSUE TITLE
Language Translation Enablement - UI

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#190]
### Background on the problem the feature will solve/improved user experience
Implement language translation via automated translation services.  These may be imperfect, but it'll be a start.
Per the Roadmap from our Design Thinking session.

### Describe the solution you'd like
Language Translation Enablement - UI

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by cstefano1** [comment]
How does this (or does this) relate to the Translation issues already logged?  #149 #150 #151

**Comment by Sabine-Justilien** [comment]
Languages to prioritize as part of deployment support:

1. English
2. Spanish
3. Korean
4. Chinese (Mandarin)
5. Chinese (Cantonese)
6. Chinese (Simplified)
7. Russian
8. Farsi
9. Hindi
10. Arabic
11. Vietnamese
12. Tagalog

**Comment by upkarlidder** [comment]
Corrected list of languages:
1 - Farsi (fa)
2 - Hindi (hi)
3 - Japanese (ja)
4 - Korean (ko)
5 - Simplified Chinese (zh-Hans)
6 - Traditional Chinese (zh-Hant)
7 - Vietnamese (vi)
8 - Arabic (ar) Egypt
9 - Russian (ru)
10 - Spanish (mexico)
11 - Tagalog
