### ISSUE TITLE
addressLabel in data vs UI string

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#194]
Looking at the code in `ui/src/components/BallotReturn/BallotReturn.vue` and `ui/src/components/EarlyVoting/EarlyVoting.vue`, I noticed that `addressLabel` is stored in the component data. I am wondering if this is best practice or should the label be stored in the UI itself? What is the advantage of storing it in the data model?

https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/e196f0c4fee5c50ef55f358330c777106ab2c675/ui/src/components/BallotReturn/BallotReturn.vue#L80

I came across this while extracting strings for translation. This string appears in the UI.

@GeraldMit @davidnixon If okay to move it out of data, I can do it as part of the translation task.

![image](https://user-images.githubusercontent.com/3187457/131155134-c90a91d3-39ec-4e1e-bf9d-d78cafda3738.png)

**Comment by davidnixon** [comment]
@upkarlidder Yes, it should be part of translation. I probably did that a long while ago thinking it might help with translation. 
Same error is in `src/components/EarlyVoting/EarlyVoting.vue`

**Comment by upkarlidder** [comment]
Thank you. I will extract it out.
