### ISSUE TITLE
Reduce Speed of Banner Images

### ISSUE THREAD

**Issue by aleggett23** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#198]
### Background on the problem the feature will solve/improved user experience
When I visit the 5/5ths voter site, I am not able to enjoy the images because they change too quickly.

### Describe the solution you'd like
An image reel that moves at a slightly slower pace to enjoy the photos.

### Tasks 
Reduce the speed of the photo exchange.

### Acceptance Criteria 
An image reel that moves at a slightly slower pace to enjoy the photos.

**Comment by upkarlidder** [comment]
@sebastianhuynh-nyc, please upload a slower gif to the repo. Thank you!

**Comment by upkarlidder** [comment]
@sebastianhuynh-nyc provided this image. Jordon will create a PR 🙏🏽 
![ebrace-vote-gif](https://user-images.githubusercontent.com/3187457/133836377-288ef9f2-6d74-4b4d-a0cf-3d885add6621.gif)

**Comment by upkarlidder** [comment]
PR merged. Thank you @jordonpowell28 for your contribution 🎉

**Comment by demilolu** [comment]
hi all, great work here. On my 15 inch screen some of the pictures seem to be cutting off, not sure how this worked before anymore. just wanted to mention, maybe post launch fix? 


<img width="1433" alt="Screen Shot 2021-09-22 at 2 09 02 PM" src="https://user-images.githubusercontent.com/3202514/134414671-02ec6798-6dbc-43b0-ada2-ec96038dd14d.png">
<img width="1225" alt="Screen Shot 2021-09-22 at 2 10 53 PM" src="https://user-images.githubusercontent.com/3202514/134414831-d382d370-82ba-42be-ba6d-3d36ae4c876c.png">
<img width="1430" alt="Screen Shot 2021-09-22 at 2 11 06 PM" src="https://user-images.githubusercontent.com/3202514/134414839-b5d6e869-0c7e-48f7-91e3-0aedb51d7fdb.png">

<img width="1548" alt="Screen Shot 2021-09-22 at 2 08 32 PM" src="https://user-images.githubusercontent.com/3202514/134414648-e70b6d5a-29c9-458f-b546-de474624e7d8.png">
