### ISSUE TITLE
Education on different types of voting

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#200]
### Background on the problem the feature will solve/improved user experience
The Presidential elections are the most attended elections even though there are local and state elections that happen across every state year-round. Users may not be aware that other elections (recall, mayoral, city council, school board) exist and require votes from registered voters. Giving an overview of the different types of elections that exist on a broad level can alert 5/5 visitors to opportunities to cast their vote.

### Describe the solution you'd like
A guide, tutorial, or video on the different types of elections that a registered voter can cast their ballot in. This would be simple to follow with more diagrams/pictures that one can consume in less than 5 minutes.

### Tasks 
- Gather information on the types of opportunities where a registered voter can cast their ballot (elections and policy)
- Define best vehicle for delivering the information (recorded video, sketched diagram) 
- Feature video in a section of the site focused on voter education

### Acceptance Criteria 
- High fidelity video or diagram that educates on where a registered voter can cast their ballots
- Proper citation or permissions for usage of others work

**Comment by demilolu** [comment]
hi @up4154 sorry we missed this, are you still interested in contributing to any of our projects?
