### ISSUE TITLE
Child Care resources 

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#203]
### Background on the problem the feature will solve/improved user experience
Marginalized communities often bear the heaviest burden when trying to exercise their right to vote especially when it comes to childcare. Parents either have to rely on family members to take care of their children during this period or take the child with them. This can be tiring for a parent especially if there are limited toilets, lack of shade, or long wait times. 

### Describe the solution you'd like
The YMCA offers numerous childcare throughout their centers. As a national organization there is greater opportunity for parents to reach out for child care during voting periods. The YMCA is a proponent of civic engagement as well as community wellness so we can point users in need of childcare to their resources. They have a ['Find your Y'](https://www.ymca.org/find-your-y?distance=175&lat=26.0517448&lng=-80.13727569999999&geolocation_geocoder_address=33004&type=branch) mapping tool that we can either pull into 5/5 or point users to the external link. 

### Tasks 
- Investigate how to incorporate the 'Find your Y' location tool as a resource for parents/guardians
- Decide if this map can be pulled into the 5/5 solution or should be pointed to via a link on 5/5

### Acceptance Criteria 
- A user can locate the 'childcare' resource in the resources tab
- A user can view the 'Find your Y' tool and select the location they need to find childcare in
- A user can connect with/ contact the selected Y and follow the process for getting childcare support

**Comment by upkarlidder** [comment]
From our scrum 09.15 meeting, the task is to replace the 
https://ymcaofcoastalga.org/news/2018/10/17/ymca-news/ymca-works-to-help-make-it-easier-for-parents-to-vote/

with
 
https://www.ymca.org/find-your-y?distance=175&lat=26.0517448&lng=-80.13727569999999&geolocation_geocoder_address=33004&type=branch

**Comment by davidnixon** [comment]
That string is in the `ui/src/views/SupportPage/SupportPage.vue` file.
Probably it's a straight search/replace.
