### ISSUE TITLE
Resources for urgent voter issues

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#206]
### Background on the problem the feature will solve/improved user experience
A user who visits the website may need help regarding urgent questions around the voting process in their region. 

### Describe the solution you'd like
A directory of voter phone hotlines or website links for urgent voter needs in their region

### Tasks 
- Research and compile resources (organization websites or phone numbers) that can serve as point of information for urgent voter issues based on state
- List out contact information in the resources tab; could possibly fit with pre-existing resources divided by state

### Acceptance Criteria 
- A user will be able to find resources around urgent voter issues based on state

**Comment by yrabun** [comment]
@Sabine-Justilien is this issue to be divided in subsections for a set of states for compilation of the information?

**Comment by Sabine-Justilien** [comment]
@yrabun we'll likely have to start breaking this out by priority states (TBD). As this evolves it may be best to list this out as an epic focusing on voter resources (urgent hotlines, childcare, etc) that vary from state to state. We can pry into what this can look like for the the future.

Issue #175 may be a duplicate of this current issue.

**Comment by Sabine-Justilien** [comment]
Report an election issue by calling:
1-866-OUR-VOTE (866-687-8683)
1-888-VE-Y-VOTA (en Español)
1-888-API-VOTE (Asian multilingual assistance)
1-844-YALLA-US (Arabic)
