### ISSUE TITLE
Team with Google?

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#21]
The Google Civic Information API is a nice effort. Perhaps IBM can partner with Google on this effort.

A partnership could help solve #20 since early voting locations and ballot drop boxes seems like a natural extension of the existing Google code.

Perhaps a partnership with Google could also help with #18 since google has location rating already. Extending the ratings to the Civic Information API might be appealing.

**Comment by orazgeldiyevanazik** [comment]
Hey guys,
We did a research on this issue. Please see the attached PDF:

[five-fifths-voter - GitJustice Team.pdf](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/files/6238853/five-fifths-voter.-.GitJustice.Team.pdf)

**Comment by cstefano1** [comment]
@davidnixon Thinks we should close this because we don't anticipate having the personnel available to making the Google Civic API better.  That would be a change in mission.
