### ISSUE TITLE
Information for youth who are using the website

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#210]
### Background on the problem the feature will solve/improved user experience
Youth are the next generation of voters but may lack context into what they need to do to become registered or even help those around them. Could we explore messaging or a CTA for youth to be more engaged in this process?

### Describe the solution you'd like
A Call to Action for youth to pre - register to vote if under 18 with resources that will enable them to do so.

### Tasks 
- Identify requirements for youth under 18 to pre-register to vote
- Identify and list organizations that provide resources for teen voters to get involved (YMCA LA Youth & Gov, Youth Voter Movement)
- Include direct links and language on teen voting in the resources section of  5/5

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by rkellis0** [comment]
- California Secretary of State website for youth 16 to 17 years to pre-register vote: https://www.sos.ca.gov/elections/pre-register-16-vote-18

- Twitter Link: https://twitter.com/CASOSvote/status/839910586838212608

- Facebook Link: https://www.facebook.com/CaliforniaSOS/photos/a.957300327615704.1073741828.179204028758675/1486371178041947/?type=3&theater

**Comment by rkellis0** [comment]
California youth under 18 requirements:
- US Citizen and California Resident
- California ID
- No Criminal record
- Not currently found mentally incompetent to vote by a court

**Comment by Sabine-Justilien** [comment]
Thanks @rkellis0!

**California Youth**
- California Secretary of State website for youth 16 to 17 years old to pre-register vote:  https://registertovote.ca.gov/ (this is a more direct link to register to vote @rkellis0. We should include the prior link versus --> https://www.sos.ca.gov/elections/pre-register-16-vote-18

**General Youth Information**
- Get Involved: https://www.ymcayag.org/vote/
- (16-18 yrs old) Preregister to vote:  https://www.ncsl.org/research/elections-and-campaigns/preregistration-for-young-voters.aspx

**Comment by Sabine-Justilien** [comment]
> * California Secretary of State website for youth 16 to 17 years old to pre-register vote: https://www.sos.ca.gov/elections/pre-register-16-vote-18
> * Twitter Link: https://twitter.com/CASOSvote/status/839910586838212608
> * Facebook Link: https://www.facebook.com/CaliforniaSOS/photos/a.957300327615704.1073741828.179204028758675/1486371178041947/?type=3&theater

Thanks for putting this together @rkellis0! I've consolidated the information to reflect the direct links to where people can register versus navigating to multiple pages.

**Comment by upkarlidder** [comment]
@Sabine-Justilien do you want the links to appear as they are? Or do you want to hyperlink a word in the sentence? Hyperlinking is more readable. If you agree, pls add sentences in the comment here as [hyperlinked](https://www.markdownguide.org/basic-syntax/#links).

![image](https://user-images.githubusercontent.com/3187457/134789403-22674ee9-6dc9-4d2c-a6b1-dbb6b13a763e.png)

**Comment by Sabine-Justilien** [comment]
> @Sabine-Justilien do you want the links to appear as they are? Or do you want to hyperlink a word in the sentence? Hyperlinking is more readable. If you agree, pls add sentences in the comment here as [hyperlinked](https://www.markdownguide.org/basic-syntax/#links).
> 
> ![image](https://user-images.githubusercontent.com/3187457/134789403-22674ee9-6dc9-4d2c-a6b1-dbb6b13a763e.png)

@upkarlidder I quoted the hyperlinks correctly in my original post. It should show up as hyperlinks in key words.
