### ISSUE TITLE
 Surface the language switcher 

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#213]
We need to surface the language switcher on the site. Currently, if you add back the commented code in App.vue, the language switch shows up on top. We want to move it to the avatar icon on the right. The avatar icon should have the languages listed in the drop down.

https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/efbe06b3c8147c6d0d5b2182e5482582da688861/ui/src/App.vue#L3

![image](https://user-images.githubusercontent.com/3187457/134227904-ffff1c2c-f171-479f-9775-5575b778b298.png)

@davidnixon suggested adding the languages to the `profile` icon on the right. @sebastianhuynh-nyc any thoughts around this?

@davidnixon is this something you can add in?

@demilolu @cstefano1 FYI

**Comment by Sabine-Justilien** [comment]
Can we change the icon to be more apparent that this is where you change the language? @sebastianhuynh-nyc

**Comment by demilolu** [comment]
can you provide a screenshot so a potential contributor knows what you're referring to?  @upkarlidder

**Comment by demilolu** [comment]
so to confirm, the ask is to create dropdown menu on the bottom right that allows people to switch the language.

**Comment by upkarlidder** [comment]
That is correct. The menu if enabled currently shows up on the top. We want it to show up as a drop down to the profile icon.

**Comment by upkarlidder** [comment]
@davidnixon @GeraldMit can you provide some hints here. @fiewor has volunteered to help.

**Comment by Fiewor** [comment]
https://ej2.syncfusion.com/vue/documentation/drop-down-list/getting-started/ 
I saw this. Looks like something that might help. Should I go ahead and attempt to use it?

**Comment by upkarlidder** [comment]
Thanks, @Fiewor. The project uses `Carbon Design Thinking` framework. We need to use components from that for this task. I am doing this tutorial to get more familiar: https://www.carbondesignsystem.com/developing/vue-tutorial/step-1

In particular, look at the [UI Shell section](https://www.carbondesignsystem.com/developing/vue-tutorial/step-1).

You can see the components here - https://vue.carbondesignsystem.com/?path=/story/components-cvcombobox--default

**Comment by GeraldMit** [comment]
Also willing to help via slack or comment here if there are questions @Fiewor

**Comment by GeraldMit** [comment]
@Fiewor hoo is this work going?

a few comments:

 I think we can change the icon from <UserAvatar20/> (https://www.carbondesignsystem.com/guidelines/icons/library/) to be something like <Language32 /> or <Translate32 /> to show it is  language or translations, or even <ListDropdown32 /> or <Settings32 /> or <SettingsAdjust32 />

You should be able to take a look at the existing buttons in ui/src/App.vue  and reuse that loop to instead populate the cv-combobox for the AppHeader in ui/src/components/AppHeader/AppHeader.vue that currently declares and uses the <UserAvatar20/>

You will probably want to have the title reflected in the language, so possibly have a coordinated value in each ui/src/plugins/<language>.json at the top adding "language"  : <translated title name> , for example for en.json, add
` "language": "English (US)",` as a new line right before `"welcomeMsg": "{0}",`

**Comment by GeraldMit** [comment]
@upkarlidder  can we close this?
