### ISSUE TITLE
Translate styled text

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#214]
Need to externalize and style a more complicated string:

```
Join us to <strong><em>get registered</em></strong
              >, <strong><em>get educated</em></strong
              >, <strong><em>get social</em></strong
              >, and <strong><em>get vocal</em></strong
              >.
```

Reference: https://vue-i18n.intlify.dev/guide/advanced/component.html#component-interpolation

@davidnixon want to take this one?

FYI @demilolu @Sabine-Justilien @cstefano1

**Comment by IfDougelseSa** [comment]
@upkarlidder I'm interested

**Comment by upkarlidder** [comment]
Thank you @IfDougelseSa 🙏🏽 . Are you able to get the site running locally? Let us know if you run into issues. And then feel free to submit a PR for review.

You will have to remove the commented out language switcher to see the translations
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/4c5cd749b1a48046be7bd80be8e73e89babc6572/ui/src/App.vue#L3

There is another [issue](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/213) to move the language [switcher to the right avatar menu](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/213).

**Comment by upkarlidder** [comment]
@IfDougelseSa, we had a [PR](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/pull/215) for this by @davidnixon. Please review when you get a chance.

I did not realize you can add a markdown component. Good to know!

@IfDougelseSa, please feel free to look at another issue. I think this was just a timing issue where you both were working on the same thing. We would still very much like your help with the other issues. 

FYI @demilolu

**Comment by upkarlidder** [comment]
@IfDougelseSa this is another UI one if you are interested - https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/213
