### ISSUE TITLE
Create GitHub action for accessibility Unit Testing 

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#216]
### Background on the problem the feature will solve/improved user experience
The team is adding in fixes for accessibility in this issue #209. We should add this as ongoing test in the CI/CD pipeline so that all new code that comes in is tested automatically.

### Describe the solution you'd like
Add a GitHub action that tests for accessibility and stops the PR or change request if the code is found not compliant to accessibility level 1 requirements as stated [here](https://www.ibm.com/able/requirements/requirements/).

Some resources
- [IBM provided automated tools](https://www.ibm.com/able/toolkit/verify/automated/)
- other open source tools [TBD]

### Tasks 
- [ ] add GitHub action that triggers on all code pushes
- [ ] will be nice if the GitHub action prints out a report after running

### Acceptance Criteria 
All new code coming into Five Fifth Voters is tested for accessibility issues when pushed into a branch or when a PR is created. Code is only deployed to production if it has passed the level 1 accessibility requirements. 

@davidnixon @GeraldMit @Sabine-Justilien @demilolu 

This was previously captured in #209.

**Comment by dmtrek14** [comment]
I'd be happy to take a look at this one if it's still available.

**Comment by demilolu** [comment]
@dmtrek14 it's yours!

**Comment by demilolu** [comment]
@dmtrek14 how's it going with this issue :) ? Are you still working on it?
