### ISSUE TITLE
No error is shown when visiting an invalid page

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#218]
**Describe the bug**
A blank page is shown when you visit an invalid site. http://localhost:3001/#/votersupport12345

**To Reproduce**
1. Serve the page locally
2. Go to `http://localhost:3001/#/votersupport12345`
3. A blank is shown to the user

**Expected behavior**
I am not sure. @davidnixon @GeraldMit thoughts?
1. Show the user a custom 404
2. take the user to the home page

**Screenshots**
![image](https://user-images.githubusercontent.com/3187457/134084787-d1d62e72-14af-4992-9994-603f61070f9c.png)

This is low priority at this time.

@demilolu @Sabine-Justilien @cstefano1

**Comment by GeraldMit** [comment]
@upkarlidder @cstefano is this resolved by #258 ? if so can we close this?
