### ISSUE TITLE
countdown clock

### ISSUE THREAD

**Issue by sebastianhuynh-nyc** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#222]
@davidnixon @upkarlidder 
can you please make the numbers smaller and give the numbers more padding between the colon 
<img width="1510" alt="Screen Shot 2021-09-21 at 1 25 45 PM" src="https://user-images.githubusercontent.com/73081956/134219263-ff81f04a-c042-41bf-adb2-8011a5df6a3a.png">

**Comment by upkarlidder** [comment]
Thank you @sebastianhuynh-nyc! This comes from the component itself. @davidnixon, I am not sure how much work this would be or what the best practice is here. Can we overwrite css that is set inside the component?

https://github.com/getanwar/vuejs-countdown/blob/86e61b9df84ae2b68d237aa23774dae183cc8f26/src/Countdown.vue#L131

**Comment by GeraldMit** [comment]
Based on what I remember, we should be able to just override the style information as we are exporting as a component.
_countdown.scss already declares some styles on .vuejs-countdown .digit and that should be the right place.

**Comment by GeraldMit** [comment]
Adding, that this seems too vary greatly depending on browser, resolution, and browser window size(width). Ex. looks pretty good at 640px on Firefox or smaller, but also gets shaky in some sizes as it is resizing, so it might be some of the size calculations between : and numbers; possibly the vw, percentage, and pixel mixed calculations?

**Comment by GeraldMit** [comment]
@sebastianhuynh-nyc @Sabine-Justilien it only takes a few minutes for me to change, but change to what? how big is smaller? Just needs something relative to work with?  otherwise I'll just do "something"

**Comment by Sabine-Justilien** [comment]
This is not a priority for deployment but is an easy fix. @sebastianhuynh-nyc Can you provide some examples of what this should look like?

**Comment by GeraldMit** [comment]
@sebastianhuynh-nyc please see countdownAndlanguagedropdown #254  I wasn't ble to get it completely centered top-bottom, required too much change the the .vue for me to complete last night as needed to redo the h3 to be part of the timer to get the text to flow on width change.

**Comment by GeraldMit** [comment]
@sebastianhuynh-nyc @upkarlidder based on the original comment, with the new size and spacing, can this item be closed? the change that merged with #254 is live and sought to address 
1. make the numbers smaller 
2. give the numbers more padding between the colon

**Comment by cstefano1** [comment]
Closing; it's already in Production.  @sebastianhuynh-nyc  Please reopen if you have any questions.
