### ISSUE TITLE
Vote early or find your polling location - no information pops up

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#228]
**Describe the bug**
In the 'Voter Journey' only 4 elections appear in the drop down menu for 'Select Election', not including California which has local and municipal elections in November. I tested the elections in Rhode Island by entering a rhode island address but it returned "No known locations. Check with your local election officials." There are several elections going on in Rhode Island between October and November so why aren't early voting or polling location returning appropriate information?

**To Reproduce**
1. Go to https://www.fivefifthsvoter.com/#/journey
2. Click on 'Vote'
3. Scroll down to 'Select Election'
4. Select Rhode Island (did not test against any other election)
5. Type in a Rhode Island address - I selected the children's museum
6. See error

**Expected behavior**
When I type in the address I would expect too see information on polling location or early voting.

**Screenshots**
<img width="640" alt="Screen Shot 2021-09-22 at 9 34 33 AM" src="https://user-images.githubusercontent.com/83599562/134367503-d4854e35-7600-495d-97d1-4f9fbcba6926.png">
<img width="627" alt="Screen Shot 2021-09-22 at 9 42 49 AM" src="https://user-images.githubusercontent.com/83599562/134367512-3cc2f02d-b682-4fee-beeb-f57db43b13ab.png">

**Additional context**

**Comment by Sabine-Justilien** [comment]
Currently this text appears when the API doesn't return information: No known locations. Check with your local election officials.

Add: Use the links provided to verify voting information. This state information may not be available through the Google Civic Information API right now.

**Comment by upkarlidder** [comment]
@Sabine-Justilien is this the final result you would like to see?

![image](https://user-images.githubusercontent.com/3187457/134756029-53308c8b-78de-44e5-9a60-d52c216e01bf.png)

**Comment by davidnixon** [comment]
@Sabine-Justilien Looks fixed already.

**Comment by Sabine-Justilien** [comment]
Language to address issue is provided. Ok to close.
