### ISSUE TITLE
Include California elections in 'Vote' Section of 'Your Voting Journey

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#229]
### Background on the problem the feature will solve/improved user experience
As we have a large audience in California, it is important we have information on California elections that are happening, including local or municipal elections (i.e. Los Angeles). 

### Describe the solution you'd like
In the drop down menu I'd like to see California, or more specifically Los Angeles, included as an option.

<img width="640" alt="Screen Shot 2021-09-22 at 9 34 33 AM" src="https://user-images.githubusercontent.com/83599562/134387064-61990fb0-13e7-4e73-8f6f-8c0b9137bd81.png">

### Tasks 
_Description of the development tasks needed to complete this issue, including tests,_ 

### Acceptance Criteria 
- user from California can select their state and find out polling location and vote early information.

**Comment by upkarlidder** [comment]
The code picks up the current elections from the google civic API. For example, last week it had the California gubernatorial recall listed. It is possible there are no immediate upcoming elections in Cali. I am not sure how far in the future it looks, but we depend on this API. @davidnixon, please chime in.


You can try it here.
https://developers.google.com/civic-information/docs/v2/elections/electionQuery

Output:
```
{
  "elections": [
    {
      "id": "2000",
      "name": "VIP Test Election",
      "electionDay": "2025-06-06",
      "ocdDivisionId": "ocd-division/country:us"
    },
    {
      "id": "7052",
      "name": "Virginia Election",
      "electionDay": "2021-11-02",
      "ocdDivisionId": "ocd-division/country:us/state:va"
    },
    {
      "id": "7078",
      "name": "Georgia Election",
      "electionDay": "2021-09-21",
      "ocdDivisionId": "ocd-division/country:us/state:ga"
    },
    {
      "id": "7145",
      "name": "North Carolina Municipal Election",
      "electionDay": "2021-10-05",
      "ocdDivisionId": "ocd-division/country:us/state:nc"
    },
    {
      "id": "7146",
      "name": "Rhode Island Municipal Election",
      "electionDay": "2021-10-05",
      "ocdDivisionId": "ocd-division/country:us/state:ri"
    }
  ],
  "kind": "civicinfo#electionsQueryResponse"
}
```

**Comment by Sabine-Justilien** [comment]
Currently this text appears when the API doesn't return information: No known locations. Check with your local election officials.

Add: Use the links provided to verify voting information. This state may not be available through the Google Civic Information API right now.

<img width="649" alt="Screen Shot 2021-09-24 at 4 25 15 PM" src="https://user-images.githubusercontent.com/83599562/134741347-76c7a32c-2f48-4cfc-a68f-021268cb4cc9.png">

**Comment by upkarlidder** [comment]
@Sabine-Justilien is this the same solutions as #228?

**Comment by upkarlidder** [comment]
@davidnixon pls see update from @Sabine-Justilien in the comment above.

https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/229#issuecomment-926930857

**Comment by davidnixon** [comment]
@Sabine-Justilien looks like Upkar fixed this one too.

**Comment by Sabine-Justilien** [comment]
Fix is included. Ok to close.
