### ISSUE TITLE
Language verification testing and general feedback - Spanish

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#238]
### Background on the problem the feature will solve/improved user experience
The Five Fifths Voter site has been translated into twelve languages. The project is looking for you to verify the translated strings 
 for Spanish on the website. Multiple contributors are welcome to participate. 

### Describe the solution you'd like
Click through the site and verify correctness in Spanish.

### Tasks 
1. Create an issue for corrections required.
2. Take a screenshot of the error and add to the issue.
3. Describe the error in the issue and recommended changes.

### Acceptance Criteria 
The fix address any grammatical issues and spelling mistakes in the translations. 

@demilolu @Sabine-Justilien

**Comment by alanverdugo** [comment]
Hi @upkarlidder , I am an IBMer from Mexico, so I can help with this! I could also help fixing the error that could be found.

I would only need to know exactly which text I would need to verify. I can only find this: https://www.fivefifthsvoter.com/ and I am not sure that is the correct one.

**Comment by upkarlidder** [comment]
Wonderful and thanks @alanverdugo! Are you in the call for code workspace? Can you please ping @Sabine-Justilien and she can get you the link. I am out on vacation this week. I will msg you when I get back. Thanks again!

Fyi @demilolu
