### ISSUE TITLE
Unit testing strategy needed (CI/CD)

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#24]
1. The `services` component needs a coverage test solution to be integrated into the CI/CD strategy. Probably with coveralls & mocha.
2. The UI also needs unit testing. See the recommendations from the Vue site for direction. https://vuejs.org/v2/guide/testing.html

**Comment by GeraldMit** [comment]
I looked at Selenium as the UI final view testing framework. 

I do not recommend Selenium as the **Only** testing for the UI, as we need tests against the UI construction layer not just the browser final render ( see the Vue recommendations) but Selenium has the benefit of having a fairly easy IDE that can be used in Chrome/Firefox as plugin, enabling non-developers to also build tests and test suites, and can run tests in headless so can be used with builds and also on the live site.
The Selenium ability to pull into the plugin and run also means that it can be used for running and updating manual tests by simply grabbing from github and downloading then browsing to the test from the plugin.

This seems like a good place to start from the middle, and have some tests, where we can then know what we need from other testing frameworks.
