### ISSUE TITLE
Workflow build action is running twice for PR

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#242]
**Describe the bug**
Workflow build action is running twice for PR

**To Reproduce**
1. Create a PR
2. See check and notice a build for the push to the branch and for the PR

**Expected behavior**
1 build should happen

**Screenshots**
![image](https://user-images.githubusercontent.com/7536103/135016535-f5be477b-85b8-4fbd-88ef-d2e98e00b044.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser NA
 - Version NA

**Additional context**
I suggest to remove the push trigger
```yaml
  push:
    branches:
      - "**"
```

**Comment by upkarlidder** [comment]
Thanks @davidnixon. That ensures build happens when people commit to their own branch (any branch). Is that desired? Looks like it triggers a double build on a PR. My original intent was to let people know if their commit is broken even before they do a PR.

I will investigate some more.
