### ISSUE TITLE
Website tabs not viewable on Mobile

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#250]
**Describe the bug**
When I am on my mobile device I cannot expand the hamburger menu to explore the voter resources that are available on the desktop application. 

**To Reproduce**
1. On you mobile device, go to fivefifthsvoter.com
2. Click on the hamburger menu (located in the top left hand corner with 4 vertical lines)
3. See error (the list doesn't expand)

**Expected behavior**
The hamburger menu should expand to show the tabs visible on the desktop version.

<img width="371" alt="Screen Shot 2021-09-29 at 12 44 41 PM" src="https://user-images.githubusercontent.com/83599562/135321410-cc2ace2b-921e-4d52-9eb2-481a1a07c08b.png">

**Screenshots**
![IMG_1386](https://user-images.githubusercontent.com/83599562/135321693-016c2968-d301-4546-8eaf-8ec1e220bae8.PNG)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Version: 15

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeraldMit** [comment]
Able to replicate in just Safari 14.1.2 browser on Mac OS Catalina. by reducing width of browser.

**Comment by GeraldMit** [comment]
Further able to confirm: happens in width adjusted Chrome and Firefox on Mac.  Likely not OS or browser specific

**Comment by GeraldMit** [comment]
Confirmed. Android all browsers as well.
