### ISSUE TITLE
Translation strings not picked up in prod

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#288]
**Describe the bug**
Translation strings are missing from the prod site. They are available in the source.

**To Reproduce**
Steps to reproduce the behavior: view `https://www.fivefifthsvoter.com/#/journey` in a non English language.

**Expected behavior**
The strings should be translated.

**Screenshots**
![image](https://user-images.githubusercontent.com/3187457/139331175-53691bb1-99d1-4624-9195-cb394134ae85.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dennybiasiolli** [comment]
Here's a fix for this issue: #298 
https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting
