### ISSUE TITLE
Text doesn't appear on Android app

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#291]
**Describe the bug**
The text "5/5 equals a whole.  A whole person…" doesn’t appear on the mobile app

**To Reproduce**
1. Go to mobile app
2. Notice missing text

**Expected behavior**
I presume the text should be there.

**Screenshots**
Screenshot of web app:
![image](https://user-images.githubusercontent.com/35705510/139348382-e6f82357-311c-4fa8-9373-88ebcfeeb0bb.png)
Screenshot of mobile app:
![image](https://user-images.githubusercontent.com/35705510/139348419-bf7c0796-ddd3-4498-93fb-4f517ee9a72e.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: Android
 - Browser: N/A (on mobile app)
 - Version 11

**Additional context**

**Comment by upkarlidder** [comment]
Thank you @cstefano1 for creating this issue. I had not noticed. Anything under 1056px, the text is taken out as the display is set to `none`. I am guessing this was a design decision taken when the code was written. @davidnixon @sebastianhuynh-nyc probably know more.

https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/4515dc4e6beef5fbc32c724e7ac28d5cd2388733/ui/src/components/Hero/_hero.scss#L210

```
.hero__description {
  @include carbon--type-style('productive-heading-03');
  display: none;
  max-width: 630px;
  margin-bottom: $spacing-06;

  @media (min-width: 1056px) {
    display: block;
  }
}
```

**Comment by cstefano1** [comment]
Closed by bot; I'm reopening.
