### ISSUE TITLE
"Your voting journey" menu hidden behind the top banner; user can't see or operate the menu

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#293]
**Describe the bug**
"Your voting journey" menu is hidden behind the top banner; user can't see or operate the menu

**To Reproduce**
1. Go to mobile app
2. Click on hamburger menu
3. Select "Your voter journey"

**Expected behavior**
User should be able to see the menu and menu should be functional

**Screenshots**
![image](https://user-images.githubusercontent.com/35705510/139348929-e9441292-8e3e-4050-a45a-db35d0532bff.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: Android
 - Browser:  N/A (on mobile app)
 - Version 11

**Additional context**

**Comment by upkarlidder** [comment]
This is now fixed. However, I would like to keep this issue open. The fix was to upload the image manually to ICR. If I ask CE to build and upload, the menu is broken. Need to look into it some mroe.
