### ISSUE TITLE
List of elections isn't sorted in a meaningful way

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#296]
**Describe the bug**

**To Reproduce**
1. Go to Your voting journey
2. Click on Vote
3. At "Select election", use pulldown to open the list of elections
4. Notice the list

**Expected behavior**
Elections would be sorted such that user can easily find their election -- perhaps strictly alpha, or maybe alpha by date?  (I think strictly alpha.)

**Screenshots**
![image](https://user-images.githubusercontent.com/35705510/139350509-dc71e9ec-15cd-452f-97b3-999f9317d74e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 
 - Version 78.15.0esr (32-bit)

**Additional context**

**Comment by bsbyrd1** [comment]
Hi there! Leaving feedback about the sorting of the supported states. What do you think of an input field that users, where users can type in their state.
