### ISSUE TITLE
Please link to fivefifthsvoter.com

### ISSUE THREAD

**Issue by garrison** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#326]
### Background on the problem the feature will solve/improved user experience

There is currently no link from https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter to https://www.fivefifthsvoter.com.  Without such a link, it is difficult to understand what this repository is about.

### Describe the solution you'd like

Add a link to the README and to the "About" box on the repository's front page.

### Tasks 

- [x] Add link to the README
- [ ] Add link to the "About" box on GitHub

**Comment by upkarlidder** [comment]
@davidnixon can you please provide info on where to put the link and language for whoever wants to pick it up? Thank you!

**Comment by rafvasq** [comment]
I embedded links in both the problem statement and the pitch sections of the README where I assumed it made sense. Happy to update based on feedback. 

I'm also unable to update the website in the repository details "About" section myself.
