### ISSUE TITLE
Voter Journey Design Update

### ISSUE THREAD

**Issue by sydbails** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#34]
**Attn**: @eveandsn @drealuc @aleggett23 @ydknorr 

[See here](https://ibm.ent.box.com/file/727493380761) for User Interface prototype.

For all questions, comments, and concerns, please post here. If there are requests or questions about copy, please ping @drealuc -- she will make the formal issue in Github.

**Comment by drealuc** [comment]
@sydbails Will collaborate with Sebastian on user journey and coordinating design changes on website
We need to estimate level of effort and completion date
