### ISSUE TITLE
Update GETSTARTED to more match Tutorial

### ISSUE THREAD

**Issue by GeraldMit** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#367]
### Background on the problem the feature will solve/improved user experience

There is a gap in the getting started where it assumes a familiarity with starting use of the tools and technology.

The tutorial covers this gap a bit, and it would be good to add to the getting started.

### Describe the solution you'd like

The developer.ibm.com site has not been updated, and perhaps the additional content should be added back to GETSTARTED.md
See Updates to Five Fifths Voter Tutorial #162
> As a person interested in contributing to the Five Fifths Voter open source project, I'm looking to complete the [tutorial](https://developer.ibm.com/tutorials/five-fifths-voter/). However, as a new developer, I'm having some issues with the tutorial.
> Problem
> Tutorial is missing a step after
> `git clone https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter`
> so that `cd services` leads to an error
> 
> Suggested Solution
> add an additional step so that we are in the right directory:
> `git clone https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter`
> `cd Five-Fifths-Voter`
> 

### Tasks 
Description of the development tasks needed to complete this issue, including tests

Go step-by-step as a completely new developer or SRE trying to do the work to do setup and run the first time.
Modify the GETSTARTED.md to add in the additional steps and words to make the step-by-step more pleasant.
Ex.: 
Prerequisites - add git
Getting Five Fifths Voter - Section before Project Setup , show the git clone. show cd Five-Fifths-Voter
In Project Setup - _Be sure to have a Node.js >=14.x_ could be improved to show how to assure you have Node.js installed, and that the version is higher than 14.x via the command line.

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by davidnixon** [comment]
I have been leaning into docker-compose on my project teams.  Want to go towards this for local dev tutorial?
It would be something like:

Launch dependencies
```shell
cd local-dev
docker-compose up
```

Launch the UI
```shell
cd ui
yarn serve
```

I have been keeping the ui out of docker-compose but I know I others prefer to launch the UI in there too.

**Comment by snehaoffice** [comment]
Thanks Gerald for creating the issue. I will work on it.
