### ISSUE TITLE
Scrape states/counties for ballot drop off locations

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#45]
See #20 for background
Currently for GA I do not see this information on the SOS site. It seems to help only by the counties which would mean for GA alone adding 150+ end points. Looking for other options.

**Comment by drealuc** [comment]
Currently there is not a roll up of county ballot boxes at the Georgia secretary of state website.

**Comment by demilolu** [comment]
@davidnixon can we discuss what the strategy going forward on tackling this should be cc  @upkarlidder
