### ISSUE TITLE
New Feature: Rate Polling Location

### ISSUE THREAD

**Issue by sydrosa** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#46]
## Description

This issue addresses the following new feature:
- A rating system for polling locations (A - F)
- An algorithm that uses different mediums and a cognitive system that determines what "grade" the voting location has
- A front end feature that allows users to see what "grade" their respective polling location and nearby polling locations have.

**Comment by drealuc** [comment]
Decompose to story and mark in ZenHub

**Comment by cstefano1** [comment]
@davidnixon Is this actually closed?  Looks like Automation closed it.
