### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#84]
- [x] api keys seems to be missing from deployment

- [x] Map not visible on absentee ballot drop off page - style issue

- [x] Markers are not cleared when you switch between early/now on the Vote page

- [x] Add more functionality to markers. I think I can add the address to the marker

- [x] GA early voting locations are not on the map. These are not in the civic api and I need to swizzle our API to be able to include them.

- [x] remove geonames.org attribution and data

**Comment by drealuc** [comment]
David is working this over the weekend

**Comment by davidnixon** [comment]
Early voting sites for GA did finally make it into the civic API. Last of the map issue is closed when #135 is merged
